language: php

sudo: false

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - DEPENDENCIES='low'
    - php: 5.6
      env:
        - DEPENDENCIES='low'
    - php: 7.0
      env:
        - SYMFONY_VERSION='^4.0'
    - php: 7.1
      env:
        - SYMFONY_VERSION='^4.0'

before_install:
  - travis_retry composer self-update

install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update "symfony/process:${SYMFONY_VERSION}"; fi;
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" = "low" ]; then composer update --prefer-lowest; fi;

script:
 - vendor/bin/phpunit

after_script:
 - php vendor/bin/coveralls -v
